name: turizm_uz
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.4
  dio: ^5.4.1
  easy_localization: ^3.0.4
  in_app_update: ^4.2.3
  gap: ^3.0.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  chuck_interceptor: ^2.0.9
  connectivity_plus: ^4.0.0

  mask_text_input_formatter: ^2.9.0

  google_maps_flutter: ^2.9.0
  geolocator: ^9.0.1
  provider: ^6.0.5
  permission_handler: ^11.3.1
  location: ^6.0.2
  yandex_mapkit: ^4.1.0
  flutter_polyline_points: ^2.1.0
#  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/lang/
    - assets/svg/
    - assets/png/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700